// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wuefpabnmpqpxrxttuqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1ZWZwYWJubXBxcHhyeHR0dXF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2NDg2ODAsImV4cCI6MjA2NDIyNDY4MH0.jwQNyR6_nRwIXUt8bHs98B7FGkmLsbyd0gDcvAaXK2E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);